# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
